name: betalac
channels:
    - conda-forge
dependencies:
    - python=3
    - pandas=1.5
    - scipy=1.9
    - matplotlib=3.6
    - numpy=1.23
    - mdtraj=1.9
    - jinja2=3.1
    - ruamel_yaml=0.15
    - jupyterlab=3
    - notebook=6
    - faunus=2.8