name: betalac
channels:
    - conda-forge
dependencies:
    - python=3
    - pandas=1
    - scipy=1
    - matplotlib=3
    - numpy=1
    - mdtraj=1.9
    - jinja2=3
    - ruamel_yaml=0.15
    - jupyterlab=3
    - notebook=6
    - faunus=2.11
